### ISSUE TITLE
Missing dictionaries funcNN and funcErrNN from .quantQ.nn

### ISSUE THREAD

**Issue by xaviweise** [hanssmail/quantQ#11]
It seems that quantQ_nn.q does not contain the definitions of .quantQ.nn.funcNN and .quantQ.nn.funcErrNN, therefore when .quantQ.nn.modelNN is called it yields an evaluation error. Adding this in the library fixes the problem and the function runs, reproducing the example in page 451 of the book

**Comment by hanssmail** [comment]
Missing functions added
