### ISSUE TITLE
.quantQ.simul.genBoxMuller does not its parameter

### ISSUE THREAD

**Issue by skeevey** [hanssmail/quantQ#2]
Function returns 2 normal variates. In Chapter 14 the results are sampled as e.g. `100?.quantQ.simul.genBoxMuller[]` (sampling 100 values from a list of two normal variates). I suspect the intention is that `.quantQ.simul.genBoxMuller[n]` return n random variates or similar

**Comment by skeptiqos** [comment]
Yes this may have been somewhat confusing, thanks for raising it. The intention for `.quantQ.simul.genBoxMuller` is to simply return 2 standard normal variates. For n normal variates,  `.quantQ.simul.getNormalVariate` should be used. 

Simplified versions of these functions have been pushed.
