### ISSUE TITLE
Typo function .quantQ.ols.logL

### ISSUE THREAD

**Issue by xaviweise** [hanssmail/quantQ#6]
When using this function I get an evaluation error at "log[2*acos-1]". The function seems to be missing a separation between "acos" and "-1", as it is actually printed in page 250 of the book.
Thanks a lot for the great library and book

**Comment by hanssmail** [comment]
Thanks for comments! We will jump on them and resolve. Btw, we would be pleased if you would commit some functions of yours or improvements into the repo directly.
